import "../styles/globals/globals.css";
import "../styles/globals/fonts.css";
import "../styles/globals/themes.css";
import { ThemeProvider } from '../context/wrappers/ThemeSwitcher';
import { ContextProvider } from "@/context/wrappers/ContextProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>
          <ThemeProvider>
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </ContextProvider>
      </body>
    </html>
  );
}
